"""initial_schema_complete

Revision ID: 85a767945dcc
Revises: None
Create Date: 2026-03-27 22:10:32.176451
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '85a767945dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('trend', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_factors', sa.Text(), nullable=True),
    sa.Column('news_analyzed', sa.Integer(), nullable=True),
    sa.Column('bullish_signals', sa.Integer(), nullable=True),
    sa.Column('bearish_signals', sa.Integer(), nullable=True),
    sa.Column('net_score', sa.Integer(), nullable=True),
    sa.Column('is_extraordinary', sa.Boolean(), nullable=True),
    sa.Column('extraordinary_reason', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_analysis_date', 'daily_analyses', ['analysis_date'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('event_name', sa.String(length=250), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('actual', sa.String(length=30), nullable=True),
    sa.Column('forecast', sa.String(length=30), nullable=True),
    sa.Column('previous', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index('idx_events_date', 'economic_events', ['event_date'], unique=False)
    op.create_table('fx_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('scraper_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('prev_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('period', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('market_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('source_country', sa.String(length=2), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('url_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('idx_news_fetched', 'market_news', ['fetched_at'], unique=False)
    op.create_index('idx_news_impact', 'market_news', ['impact_level'], unique=False)
    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('usdpen', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('usdpen_prev', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('usdpen_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('gold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gold_prev', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gold_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('oil', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('oil_prev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('oil_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sp500', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sp500_prev', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sp500_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('nasdaq', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nasdaq_prev', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nasdaq_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('dxy', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('dxy_prev', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('dxy_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('vix', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('vix_prev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('vix_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('copper', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('copper_prev', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('copper_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('treasury_10y', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('treasury_10y_prev', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('treasury_10y_chg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('eurusd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eurusd_prev', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eurusd_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('eem', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eem_prev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eem_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('epu', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('epu_prev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('epu_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('usdjpy', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('usdjpy_prev', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('usdjpy_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('btc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('btc_prev', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('btc_chg_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_snap_time', 'market_snapshots', ['captured_at'], unique=False)
    op.create_table('risk_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('score_min', sa.Integer(), nullable=True),
    sa.Column('score_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sanctions_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('name_normalized', sa.String(length=400), nullable=True),
    sa.Column('aliases_json', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('program', sa.String(length=300), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_entries_name_normalized'), 'sanctions_entries', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_sanctions_entries_source'), 'sanctions_entries', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('Master', 'Trader', 'Operador', 'Middle Office', 'App', 'Web')", name='check_user_role'),
    sa.CheckConstraint("status IN ('Activo', 'Inactivo')", name='check_user_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bank_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_pen', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initial_balance_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initial_balance_pen', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('balance_pen >= 0', name='check_balance_pen_positive'),
    sa.CheckConstraint('balance_usd >= 0', name='check_balance_usd_positive'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name', name='uq_bank_name')
    )
    op.create_index(op.f('ix_bank_balances_bank_name'), 'bank_balances', ['bank_name'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('persona_contacto', sa.String(length=200), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('requires_password_change', sa.Boolean(), nullable=True),
    sa.Column('dni_front_url', sa.String(length=500), nullable=True),
    sa.Column('dni_back_url', sa.String(length=500), nullable=True),
    sa.Column('dni_representante_front_url', sa.String(length=500), nullable=True),
    sa.Column('dni_representante_back_url', sa.String(length=500), nullable=True),
    sa.Column('ficha_ruc_url', sa.String(length=500), nullable=True),
    sa.Column('validation_oc_url', sa.String(length=500), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=6), nullable=True),
    sa.Column('used_referral_code', sa.String(length=6), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('referral_pips_earned', sa.Float(), nullable=True),
    sa.Column('referral_pips_available', sa.Float(), nullable=True),
    sa.Column('referral_completed_uses', sa.Integer(), nullable=True),
    sa.Column('referral_total_uses', sa.Integer(), nullable=True),
    sa.Column('bank_accounts_json', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account_pen', sa.String(length=100), nullable=True),
    sa.Column('bank_account_usd', sa.String(length=100), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('has_complete_documents', sa.Boolean(), nullable=False),
    sa.Column('operations_without_docs_count', sa.Integer(), nullable=True),
    sa.Column('operations_without_docs_limit', sa.Integer(), nullable=True),
    sa.Column('max_amount_without_docs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('inactive_reason', sa.String(length=200), nullable=True),
    sa.Column('documents_pending_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referred_by'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_dni'), 'clients', ['dni'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_referral_code'), 'clients', ['referral_code'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('contact_person', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('complaint_type', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('evidence_image_url', sa.Text(), nullable=True),
    sa.Column('resolution_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("complaint_type IN ('Reclamo', 'Queja')", name='check_complaint_type'),
    sa.CheckConstraint("document_type IN ('DNI', 'CE', 'RUC')", name='check_complaint_document_type'),
    sa.CheckConstraint("status IN ('Pendiente', 'En Revisión', 'Resuelto')", name='check_complaint_status'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_complaints_document_number'), 'complaints', ['document_number'], unique=False)
    op.create_table('compliance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('auto_flag', sa.Boolean(), nullable=True),
    sa.Column('auto_block', sa.Boolean(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sell_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=10), nullable=False),
    sa.Column('old_buy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('new_buy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('old_sell', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('new_sell', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('buy_delta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sell_delta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('buy_delta_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sell_delta_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['fx_competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rate_current',
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sell_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('prev_buy_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('prev_sell_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scrape_ok', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['fx_competitors.id'], ),
    sa.PrimaryKeyConstraint('competitor_id')
    )
    op.create_table('fx_rate_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sell_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['fx_competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fx_history_competitor_time', 'fx_rate_history', ['competitor_id', 'scraped_at'], unique=False)
    op.create_table('trader_daily_profits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profit_date', sa.Date(), nullable=False),
    sa.Column('profit_amount_pen', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profit_date', name='uq_trader_profit_date')
    )
    op.create_index(op.f('ix_trader_daily_profits_profit_date'), 'trader_daily_profits', ['profit_date'], unique=False)
    op.create_index(op.f('ix_trader_daily_profits_user_id'), 'trader_daily_profits', ['user_id'], unique=False)
    op.create_table('trader_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('goal_amount_pen', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('goal_amount_pen >= 0', name='check_goal_positive'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='check_month_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='uq_trader_month_year')
    )
    op.create_index(op.f('ix_trader_goals_user_id'), 'trader_goals', ['user_id'], unique=False)
    op.create_table('client_risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('risk_level_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=True),
    sa.Column('has_legal_issues', sa.Boolean(), nullable=True),
    sa.Column('in_restrictive_lists', sa.Boolean(), nullable=True),
    sa.Column('high_volume_operations', sa.Boolean(), nullable=True),
    sa.Column('pep_type', sa.String(length=50), nullable=True),
    sa.Column('pep_position', sa.String(length=200), nullable=True),
    sa.Column('pep_entity', sa.String(length=200), nullable=True),
    sa.Column('pep_designation_date', sa.Date(), nullable=True),
    sa.Column('pep_end_date', sa.Date(), nullable=True),
    sa.Column('pep_notes', sa.Text(), nullable=True),
    sa.Column('kyc_status', sa.String(length=50), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
    sa.Column('kyc_verified_by', sa.Integer(), nullable=True),
    sa.Column('kyc_notes', sa.Text(), nullable=True),
    sa.Column('dd_level', sa.String(length=50), nullable=True),
    sa.Column('dd_last_review', sa.DateTime(), nullable=True),
    sa.Column('dd_next_review', sa.DateTime(), nullable=True),
    sa.Column('scoring_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['kyc_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_level_id'], ['risk_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_operator_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount_pen', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source_account', sa.String(length=100), nullable=True),
    sa.Column('destination_account', sa.String(length=100), nullable=True),
    sa.Column('client_deposits_json', sa.Text(), nullable=True),
    sa.Column('client_payments_json', sa.Text(), nullable=True),
    sa.Column('operator_proofs_json', sa.Text(), nullable=True),
    sa.Column('modification_logs_json', sa.Text(), nullable=True),
    sa.Column('operator_comments', sa.Text(), nullable=True),
    sa.Column('payment_proof_url', sa.String(length=500), nullable=True),
    sa.Column('operator_proof_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_read_by_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('in_process_since', sa.DateTime(), nullable=True),
    sa.CheckConstraint("operation_type IN ('Compra', 'Venta')", name='check_operation_type'),
    sa.CheckConstraint("origen IN ('sistema', 'plataforma', 'app', 'web')", name='check_operation_origen'),
    sa.CheckConstraint("status IN ('Pendiente', 'En proceso', 'Completada', 'Cancelado', 'Expirada')", name='check_operation_status'),
    sa.CheckConstraint('amount_usd > 0', name='check_amount_usd_positive'),
    sa.CheckConstraint('exchange_rate > 0', name='check_exchange_rate_positive'),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_assigned_operator_id'), 'operations', ['assigned_operator_id'], unique=False)
    op.create_index(op.f('ix_operations_client_id'), 'operations', ['client_id'], unique=False)
    op.create_index(op.f('ix_operations_created_at'), 'operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_operations_operation_id'), 'operations', ['operation_id'], unique=True)
    op.create_index(op.f('ix_operations_origen'), 'operations', ['origen'], unique=False)
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_index(op.f('ix_operations_user_id'), 'operations', ['user_id'], unique=False)
    op.create_table('restrictive_list_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('pep_checked', sa.Boolean(), nullable=True),
    sa.Column('pep_result', sa.String(length=50), nullable=True),
    sa.Column('pep_details', sa.Text(), nullable=True),
    sa.Column('ofac_checked', sa.Boolean(), nullable=True),
    sa.Column('ofac_result', sa.String(length=50), nullable=True),
    sa.Column('ofac_details', sa.Text(), nullable=True),
    sa.Column('onu_checked', sa.Boolean(), nullable=True),
    sa.Column('onu_result', sa.String(length=50), nullable=True),
    sa.Column('onu_details', sa.Text(), nullable=True),
    sa.Column('uif_checked', sa.Boolean(), nullable=True),
    sa.Column('uif_result', sa.String(length=50), nullable=True),
    sa.Column('uif_details', sa.Text(), nullable=True),
    sa.Column('interpol_checked', sa.Boolean(), nullable=True),
    sa.Column('interpol_result', sa.String(length=50), nullable=True),
    sa.Column('interpol_details', sa.Text(), nullable=True),
    sa.Column('denuncias_checked', sa.Boolean(), nullable=True),
    sa.Column('denuncias_result', sa.String(length=50), nullable=True),
    sa.Column('denuncias_details', sa.Text(), nullable=True),
    sa.Column('otras_listas_checked', sa.Boolean(), nullable=True),
    sa.Column('otras_listas_result', sa.String(length=50), nullable=True),
    sa.Column('otras_listas_details', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('emisor_ruc', sa.String(length=11), nullable=False),
    sa.Column('emisor_razon_social', sa.String(length=200), nullable=False),
    sa.Column('emisor_direccion', sa.String(length=300), nullable=True),
    sa.Column('cliente_tipo_documento', sa.String(length=10), nullable=True),
    sa.Column('cliente_numero_documento', sa.String(length=20), nullable=False),
    sa.Column('cliente_denominacion', sa.String(length=200), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=300), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('gravada', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exonerada', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('igv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nubefact_response', sa.Text(), nullable=True),
    sa.Column('nubefact_enlace_pdf', sa.String(length=500), nullable=True),
    sa.Column('nubefact_enlace_xml', sa.String(length=500), nullable=True),
    sa.Column('nubefact_aceptada_por_sunat', sa.Boolean(), nullable=True),
    sa.Column('nubefact_sunat_description', sa.Text(), nullable=True),
    sa.Column('nubefact_sunat_note', sa.Text(), nullable=True),
    sa.Column('nubefact_codigo_hash', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_operation_id'), 'invoices', ['operation_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('transaction_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('unusual_amount', sa.Boolean(), nullable=True),
    sa.Column('unusual_frequency', sa.Boolean(), nullable=True),
    sa.Column('structuring', sa.Boolean(), nullable=True),
    sa.Column('rapid_movement', sa.Boolean(), nullable=True),
    sa.Column('client_avg_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deviation_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_to_uif', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['compliance_alerts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_documents')
    op.drop_table('transaction_monitoring')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_operation_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('compliance_alerts')
    op.drop_table('restrictive_list_checks')
    op.drop_index(op.f('ix_operations_user_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_index(op.f('ix_operations_origen'), table_name='operations')
    op.drop_index(op.f('ix_operations_operation_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_created_at'), table_name='operations')
    op.drop_index(op.f('ix_operations_client_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_assigned_operator_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_table('client_risk_profiles')
    op.drop_index(op.f('ix_trader_goals_user_id'), table_name='trader_goals')
    op.drop_table('trader_goals')
    op.drop_index(op.f('ix_trader_daily_profits_user_id'), table_name='trader_daily_profits')
    op.drop_index(op.f('ix_trader_daily_profits_profit_date'), table_name='trader_daily_profits')
    op.drop_table('trader_daily_profits')
    op.drop_index('idx_fx_history_competitor_time', table_name='fx_rate_history')
    op.drop_table('fx_rate_history')
    op.drop_table('fx_rate_current')
    op.drop_table('fx_change_events')
    op.drop_table('exchange_rates')
    op.drop_table('compliance_rules')
    op.drop_table('compliance_audit')
    op.drop_index(op.f('ix_complaints_document_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_clients_referral_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_dni'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_bank_balances_bank_name'), table_name='bank_balances')
    op.drop_table('bank_balances')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sanctions_entries_source'), table_name='sanctions_entries')
    op.drop_index(op.f('ix_sanctions_entries_name_normalized'), table_name='sanctions_entries')
    op.drop_table('sanctions_entries')
    op.drop_table('risk_levels')
    op.drop_index('idx_market_snap_time', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('market_signals')
    op.drop_index('idx_news_impact', table_name='market_news')
    op.drop_index('idx_news_fetched', table_name='market_news')
    op.drop_table('market_news')
    op.drop_table('macro_indicators')
    op.drop_table('fx_competitors')
    op.drop_index('idx_events_date', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('idx_daily_analysis_date', table_name='daily_analyses')
    op.drop_table('daily_analyses')
    # ### end Alembic commands ###