"""Remove unique constraint from client email to allow multiple clients with same email

Revision ID: k3l4m5n6o7p8
Revises: j2k3l4m5n6o7
Create Date: 2024-12-05 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'k3l4m5n6o7p8'
down_revision = 'j2k3l4m5n6o7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar índice UNIQUE del campo email en la tabla clients
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_email_key', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restaurar índice UNIQUE del campo email en la tabla clients
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('clients_email_key', ['email'])
    # ### end Alembic commands ###
